### PR TITLE
[IOTDB-2953] IoTDB benchmark writeSchema bug

### PR DESCRIPTION
**Pull request by jun0315**
see https://issues.apache.org/jira/browse/IOTDB-2953

### CODE REVIEW

**Comment by jun0315** [comment]
PTAL~ @SteveYurongSu @SpriCoder

**Review by SpriCoder — APPROVED** [review]
LGTM

**Review by SteveYurongSu — APPROVED** [review]

**Comment by SteveYurongSu** [comment]
@SpriCoder Help us merge it into master :D

**Comment by SpriCoder** [comment]
@SteveYurongSu Get it!

**Pull request merged**
